### ISSUE TITLE
sincosf returns wrong results on interval (7*pi/4, 9*pi/4)

### ISSUE THREAD

**Issue by ajfrantz** [rust-lang/libm#232] opened 2019-11-22 17:07 UTC
Using `libm` 0.2.0 / master `a5e39d8f1ad2ad669e62565f98f1dc86ea5fed96`, this simple test case exercising `2*pi` symmetry:
```
#[cfg(test)]
mod tests {
    use libm::sincosf;

    fn d2r(d: f32) -> f32 {
        use std::f32::consts::PI;
        d * PI / 180.
    }

    #[test]
    fn test_sincosf() {
        assert_eq!(sincosf(d2r(330.)), sincosf(d2r(330. - 360.)));
    }
}
```
Fails (for non-limited-precision reasons), with the message:
```
---- tests::test_sincosf stdout ----
thread 'tests::test_sincosf' panicked at 'assertion failed: `(left == right)`
  left: `(0.86602545, -0.4999999)`,
 right: `(-0.5, 0.8660254)`', src/lib.rs:12:9
```
Precision issues aside, note that the sin/cos components are reversed.

Some quick binary searching shows that this condition persists across the interval of [316, 404] degrees, which is to say it appears to affect (7*pi/4, 9*pi/4) rad.

**Comment by CryZe** [comment] 2019-11-22 17:30
Potentially related to this fix? https://github.com/rust-lang/libm/pull/229

**Comment by CryZe** [comment] 2019-11-22 17:32
Doesn't seem like a regression caused by it, but it seems like it's yet another mismatch in the port:

Rust: https://github.com/rust-lang/libm/pull/229/files#diff-0c8e95d41d2a4f7c514c05e08b634751R90-R98

MUSL: https://github.com/bpowers/musl/blob/94cb2ec2a0ffcb47d24dbf7a30e462505396cf54/src/math/sincosf.c#L82-L86

**Comment by CryZe** [comment] 2019-11-22 17:34
Yeah looks like cos and sin are swapped there. sin should be assigned to sin and cos to cos. Seems like a copy paste mistake.

**Closed** 2019-11-22 19:16 UTC
