### ISSUE TITLE
Make functions in this crate `const`?

### ISSUE THREAD

**Issue by JSorngard** [rust-lang/libm#310] opened 2024-10-18 07:18 UTC
Now that `const_float_arithmetic` has been stabilized, will the functions in this crate be made `const` where possible? Or is this not in scope due to MSRV policy?

**Comment by tgross35** [comment] 2024-10-18 08:21
The stabilization definitely would make it possible for some of these functions to work in `const` contexts. However, I don't think that is an API guarantee we want to make because it would be a pretty significant limit on flexibility (anything that uses SIMD, assembly, or generic algorithms would no longer usable).

I think the better solution is to just move the math functions from `std` to `core`, and then make those `const` using the host machine's implementation. This is already planned but we do need to improve some things in this crate before it is possible (e.g. fix rounding errors, make sure our implementation is performant enough to ship).

**Comment by tgross35** [comment] 2024-10-18 08:31
I am going to close this since I don't think we will make any changes in this crate's public API. I brought the topic of const float math up on Zulip since I don't think it has been discussed too much before https://rust-lang.zulipchat.com/#narrow/channel/146212-t-compiler.2Fconst-eval/topic/Const.20float.20math (feel free to drop by there if you have any interest working on it)

**Closed by tgross35** 2024-10-18 08:31 UTC

**Comment by burrbull** [comment] 2024-10-19 11:15
I'd wait for 1.83 (beta now): https://github.com/rust-lang/rust/pull/129195

**Comment by kpreid** [comment] 2024-12-23 16:28
> I think the better solution is to just move the math functions from std to core, and then make those const using the host machine's implementation.

Note that the Zulip discussion didn’t particularly reach a conclusion in favor of this plan, and in particular RalfJ opined that it is likely unsound:

> so... I think it is a hard constraint that all compile-time float support *must* be done via fully deterministic implementations that behave the same across all platforms

Also, applications may benefit from access to this same kind of determinism. For example, today I use `libm` not only for `no_std` compatibility, but also so that I can compute reproducible results. (Of course, future versions of `libm` may change algorithm and break those results, but dependency versions are controllable.)

Supporting `const` still might be declared infeasible for `libm` (as noted above about SIMD etc.); I just wanted to point out that _this particular alternate plan_ seems like it is not going to happen.

**Comment by burrbull** [comment] 2024-12-23 17:03
> Supporting `const` still might be declared infeasible for `libm` (as noted above about SIMD etc.); I just wanted to point out that _this particular alternate plan_ seems like it is not going to happen.

What you think about 2-level implementation?
- 1st level: constant naive fallible implementation.
```rust
pub const fn try_sin() -> Result<f32, Error> {};
```
- 2nd level: wrapper which can choose implementation (naive, intrinsic, SIMD, etc.) and fails on `Error`.
```rust
pub fn sin() -> f32 {}
```
